apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: redpanda-ingress
  namespace: redpanda
spec:
  entryPoints:
    - redpanda
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - kind: Service
          name: redpanda-console
          namespace: redpanda
          port: 8080
